"""update listing types to service focus

Revision ID: 60d0d304e215
Revises: 809aaa2f5408
Create Date: 2026-03-05 15:12:30.641072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60d0d304e215'
down_revision: Union[str, Sequence[str], None] = '809aaa2f5408'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
