"""add profile fields and sync schema

Revision ID: 809aaa2f5408
Revises: 2a0b8f4c7ff0
Create Date: 2026-03-04 21:30:47.178943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '809aaa2f5408'
down_revision: Union[str, Sequence[str], None] = '2a0b8f4c7ff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the Enum type first
    op.execute("CREATE TYPE experiencelevel AS ENUM ('beginner', 'intermediate', 'expert')")
    op.add_column('users', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('users', sa.Column('skill_tags', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('experience_level', sa.Enum('beginner', 'intermediate', 'expert', name='experiencelevel'), nullable=True))
    op.add_column('users', sa.Column('portfolio_links', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('is_available', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('users', sa.Column('profile_picture_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_picture_url')
    op.drop_column('users', 'is_available')
    op.drop_column('users', 'portfolio_links')
    op.drop_column('users', 'experience_level')
    op.drop_column('users', 'skill_tags')
    op.drop_column('users', 'bio')
    op.execute("DROP TYPE experiencelevel")
    # ### end Alembic commands ###
